### ISSUE TITLE
When starting a new game the rule presented on page is wrong  THIS IS URGENT

### ISSUE THREAD

**Issue by Akunen** [jamktiko/juomapelit-app#32]

**Comment by Konnad** [comment]
I'm on it!!

-Janne

**Comment by Konnad** [comment]
I fixed it! It was a minor programming error by the programmer. ![istockphoto-544662460-612x612.jpg](https://images.zenhubusercontent.com/63245517e0f66dcc3c997a54/32e09db7-377b-456a-9943-57fb49ac2e73)

**Comment by Akunen** [comment]
Well done Janne! :)
