### ISSUE TITLE
After starting a new game, the card counter doesnt go up to 52 thus päätä vuorosi button is showing at the end of the second round

### ISSUE THREAD

**Issue by Akunen** [jamktiko/juomapelit-app#33]

**Comment by Konnad** [comment]
Alrighty! I'm on it! You can count on me!

Best regards,
Janne Matela
Junior Developer
![2232323.jpg](https://images.zenhubusercontent.com/63245517e0f66dcc3c997a54/aa45cc55-2dbf-410b-9469-99ca2e3abf31)

**Comment by Konnad** [comment]
Bug is fixed. The programmer had done a little oopsie. When pressing the "Uusi Peli" button, the function that is linked to that button didn't push and splice the last card from the deck, so the counter got a little fucky.
![st,small,845x845-pad,1000x1000,f8f8f8.jpg](https://images.zenhubusercontent.com/63245517e0f66dcc3c997a54/b16798fd-a6ff-4943-9d95-68f7a76f8f29)

**Comment by Akunen** [comment]
Hey Janne. WOW! That was quick :) well done! The QA -team is very happy with your work,

Have a spooky October

-Aku Järvinen Junior cloud engineer.
