### ISSUE TITLE
Komponenttirakenne

### ISSUE THREAD

**Issue by juliuskelja** [jamktiko/juomapelit-app#36]
USER STORY
Devaajana haluan, että komponentit ja työtilan infrastruktuuri ovat siistit ja selkeät.

## Acceptance Criteria
- [x] Komponenttien suunnittelu
- [x] Kansiorakenne
- [x] Komponentit kaikille ikkunoille/elementeille

**Comment by AA3098** [comment]
Base groundwork is done, but it can always be improved upon!
![image.png](https://images.zenhubusercontent.com/632457b452b407883a8c0845/5ba9d052-477e-4dbe-a673-beb9b42acfdd)
