### ISSUE TITLE
Selainnäkymässä kortti on ikkunan vasemmassa reunassa.

### ISSUE THREAD

**Issue by Akunen** [jamktiko/juomapelit-app#40]

**Comment by Akunen** [comment]
So it appears that the card is on the left side of the browser window ![kuva.png](https://images.zenhubusercontent.com/632456ac2544bdeee0c9fcf9/2e439ac1-fc7a-4e3c-afe2-a97d2e9f7ac6)

**Comment by juliuskelja** [comment]
This has been fixed in the current version. No worries!
