### ISSUE TITLE
Card bug

### ISSUE THREAD

**Issue by Konnad** [jamktiko/juomapelit-app#42]
When finishing one round of the game, the card that is the last one, doesn't update when starting a game.

**Comment by Akunen** [comment]
![kuva.png](https://images.zenhubusercontent.com/632456ac2544bdeee0c9fcf9/ffec6078-4874-4cd5-8859-af366c011546)

**Comment by Konnad** [comment]
![image.psd.png](https://images.zenhubusercontent.com/63245517e0f66dcc3c997a54/cfc0e6d1-2631-4794-a1ba-8083684a3b48)

**Comment by Konnad** [comment]
Bug is now fixed on the V0.0.2 branch!

Detailed "patch" notes you can read from the branch history.

Best regards,
Janne Matela, Junior Web Developer.
![Programming-Memes-Programmer-while-sleeping.jpg](https://images.zenhubusercontent.com/63245517e0f66dcc3c997a54/61d9233b-7638-43e6-b12d-0fab0f027a7f)
