### ISSUE TITLE
First card not counting

### ISSUE THREAD

**Issue by juliuskelja** [jamktiko/juomapelit-app#44]
After adding the backside of the card to the pile, the code counts it as one of the 52 cards. Can someone fix the code, so the function doesn't count the first card as a played card?

**Comment by Konnad** [comment]
I'm on it! You can count on me!!

Best regards,
Janne Matela
The Junior Developer
![fuhheruhrfguhuh.jpg](https://images.zenhubusercontent.com/63245517e0f66dcc3c997a54/66b5ad75-d21f-4917-8200-d08cedc4f23a)

**Comment by Konnad** [comment]
Haha! It took a while, but it is done now!
I will close this issue now.!

Best regards,
Janne Matela
The Junior Developer
![1 wygpuRlFHFxNtihw9WQv7Q.png](https://images.zenhubusercontent.com/63245517e0f66dcc3c997a54/87613a3c-1a86-42d9-b20f-d9a033494069)
