### ISSUE TITLE
Pelikortit tietokannasta

### ISSUE THREAD

**Issue by juliuskelja** [jamktiko/juomapelit-app#50]
USER STORY
Devaajana haluan, että pelikorttien tiedot ja data tulevat tietokannasta.

## Acceptance Criteria
- [x] Kun korttia painetaan, tulostuu random kortin data, joka tulee tietokannasta
- [x] Tietokannasta löytyy pelikortit ja niiden data (rank, suit, säännöt)
- [x] Data siirtyy backendistä frontendiin

## Definition of Done
- [x] Acceptance Criteria tehty
- [x] Koodi testattua ja menee läpi

**Comment by Konnad** [comment]
Kortin tiedot tulevat tietokannasta ja menee testeistä läpi.
